-- Kho tham chiếu chung (@mention) — xem lib/reference-elements.ts

create table if not exists reference_elements (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  type text not null check (type in ('character', 'location', 'prop')),
  name text not null,
  element_id text not null,
  description text,
  image_urls text[] not null default '{}',
  created_at timestamptz not null default now()
);

create unique index if not exists reference_elements_user_element_id_idx
  on reference_elements(user_id, element_id);

alter table reference_elements enable row level security;
