export type MiniApp = {
  id: string;
  name: string;
  description: string;
  category: "anh" | "van-ban" | "video" | "am-thanh";
  icon: "photo" | "file-text" | "caption" | "translate" | "sentiment" | "sparkles" | "film" | "shirt";
  creditCost: number;
  popular?: boolean;
  isNew?: boolean;
  inputType: "text" | "image" | "image-gen" | "video-gen" | "outfit-swap" | "dialogue-video" | "motion-transfer" | "video-transform" | "story-video";
  outputType?: "text" | "image" | "video";
  inputLabel: string;
  inputPlaceholder: string;
  demoInput: string;
  demoOutput: string;
  usageCount: number;
  rating: number;
};

export const CATEGORIES: Record<MiniApp["category"], string> = {
  "anh": "Ảnh",
  "van-ban": "Văn bản",
  "video": "Video",
  "am-thanh": "Âm thanh",
};

export const MINI_APPS: MiniApp[] = [
  {
    id: "viet-mo-ta-san-pham",
    name: "Viết mô tả sản phẩm từ ảnh",
    description: "Tải ảnh sản phẩm lên, AI viết mô tả bán hàng hấp dẫn trong vài giây.",
    category: "anh",
    icon: "photo",
    creditCost: 15,
    popular: true,
    inputType: "image",
    inputLabel: "Tải ảnh sản phẩm lên",
    inputPlaceholder: "",
    demoInput: "Ảnh: son môi lì màu đỏ cam, vỏ hộp nhũ vàng",
    demoOutput:
      "Thỏi son lì màu đỏ cam trẻ trung, vỏ hộp nhũ vàng sang trọng. Chất son mịn, lên màu chuẩn, giữ màu suốt 8 tiếng. Phù hợp mọi tone da, tôn dáng môi tự nhiên.",
    usageCount: 1240,
    rating: 4.8,
  },
  {
    id: "tom-tat-van-ban",
    name: "Tóm tắt văn bản",
    description: "Dán văn bản dài, nhận bản tóm tắt ngắn gọn giữ đúng ý chính.",
    category: "van-ban",
    icon: "file-text",
    creditCost: 5,
    popular: true,
    inputType: "text",
    inputLabel: "Dán văn bản cần tóm tắt",
    inputPlaceholder: "Dán đoạn văn bản dài vào đây...",
    demoInput:
      "Bài viết dài 1200 từ về xu hướng thương mại điện tử Việt Nam 2026, bao gồm số liệu tăng trưởng, hành vi người tiêu dùng, và dự báo các ngành hàng tiềm năng...",
    demoOutput:
      "Thương mại điện tử Việt Nam 2026 tăng trưởng 22% so với năm trước, dẫn đầu bởi ngành hàng làm đẹp và thực phẩm chức năng. Người tiêu dùng ưu tiên mua sắm qua livestream, thanh toán không tiền mặt chiếm 68% giao dịch.",
    usageCount: 3450,
    rating: 4.6,
  },
  {
    id: "viet-caption",
    name: "Viết caption Facebook/TikTok",
    description: "Nhập chủ đề, AI viết caption thu hút kèm hashtag phù hợp.",
    category: "van-ban",
    icon: "caption",
    creditCost: 8,
    popular: true,
    inputType: "text",
    inputLabel: "Chủ đề bài đăng",
    inputPlaceholder: "Ví dụ: khai trương cửa hàng mỹ phẩm, giảm giá 20%",
    demoInput: "Khai trương cửa hàng mỹ phẩm, giảm giá 20% trong 3 ngày đầu",
    demoOutput:
      "🎉 KHAI TRƯƠNG RỘN RÀNG — GIẢM NGAY 20%!\nGhé shop trong 3 ngày đầu để nhận ưu đãi cực hời, số lượng có hạn nha cả nhà 💄✨\n#khaitruong #mypham #giamgia #uudai",
    usageCount: 2890,
    rating: 4.7,
  },
  {
    id: "dich-da-ngon-ngu",
    name: "Dịch đa ngôn ngữ",
    description: "Dịch tự nhiên giữa tiếng Việt và nhiều ngôn ngữ khác, không dịch máy cứng nhắc.",
    category: "van-ban",
    icon: "translate",
    creditCost: 6,
    isNew: true,
    inputType: "text",
    inputLabel: "Văn bản cần dịch",
    inputPlaceholder: "Nhập văn bản và ngôn ngữ đích...",
    demoInput: "Việt → Anh: Sản phẩm này rất được lòng khách hàng trẻ.",
    demoOutput: "This product has really won over young customers.",
    usageCount: 610,
    rating: 4.5,
  },
  {
    id: "tao-anh-quang-cao",
    name: "Tạo ảnh quảng cáo sản phẩm",
    description: "Tải ảnh sản phẩm thật lên (không bắt buộc), mô tả bối cảnh mong muốn, AI tạo ảnh quảng cáo mới giữ đúng sản phẩm.",
    category: "anh",
    icon: "sparkles",
    creditCost: 20,
    isNew: true,
    inputType: "image-gen",
    outputType: "image",
    inputLabel: "Mô tả bối cảnh ảnh quảng cáo muốn tạo",
    inputPlaceholder: "Ví dụ: đặt sản phẩm lên nền gỗ sang trọng, ánh sáng studio ấm, phong cách cao cấp",
    demoInput: "Đặt thỏi son lên nền đá cẩm thạch trắng, ánh sáng studio, phong cách cao cấp",
    demoOutput: "Ảnh sản phẩm mới giữ đúng hình dáng và màu sắc thỏi son, đặt trên nền đá cẩm thạch sang trọng.",
    usageCount: 0,
    rating: 5.0,
  },
  {
    id: "tao-video-quang-cao",
    name: "Tạo video từ ảnh",
    description: "Tải 1 ảnh nhân vật (không bắt buộc), mô tả chuyển động muốn tạo, AI tạo video ngắn 4-5 giây.",
    category: "video",
    icon: "film",
    creditCost: 400,
    isNew: true,
    inputType: "video-gen",
    outputType: "video",
    inputLabel: "Mô tả video muốn tạo",
    inputPlaceholder: "Ví dụ: sản phẩm xoay tròn trên bàn, ánh sáng studio, chuyển động mượt",
    demoInput: "Chai nước hoa xoay tròn chậm trên nền đen, ánh sáng lung linh",
    demoOutput: "Video 4 giây, chai nước hoa xoay 360 độ mượt mà, ánh sáng phản chiếu đẹp.",
    usageCount: 0,
    rating: 5.0,
  },
  {
    id: "video-truoc-sau",
    name: "Video trước/sau",
    description: "Tải ảnh \"trước\" + ảnh \"sau\", AI tạo video chuyển cảnh mượt mà từ trạng thái này sang trạng thái kia — phù hợp mỹ phẩm/làm đẹp, đổi trang phục, unboxing sản phẩm.",
    category: "video",
    icon: "film",
    creditCost: 23,
    isNew: true,
    inputType: "video-transform",
    outputType: "video",
    inputLabel: "Ảnh trước và ảnh sau",
    inputPlaceholder: "",
    demoInput: "Ảnh da mặt xỉn màu (trước) + ảnh da mặt sáng mịn (sau)",
    demoOutput: "Video chuyển cảnh mượt từ ảnh trước sang ảnh sau trong 4-5 giây.",
    usageCount: 0,
    rating: 5.0,
  },
  {
    id: "nhay-theo-video-mau",
    name: "Nhảy theo video mẫu",
    description: "Tải 1 ảnh nhân vật + 1 video mẫu chuyển động (tối đa 10 giây), AI cho nhân vật nhảy/chuyển động theo đúng video mẫu.",
    category: "video",
    icon: "film",
    creditCost: 56,
    isNew: true,
    inputType: "motion-transfer",
    outputType: "video",
    inputLabel: "Ảnh nhân vật + video mẫu chuyển động",
    inputPlaceholder: "",
    demoInput: "Ảnh cô gái đứng thẳng + video mẫu 1 người đang nhảy",
    demoOutput: "Video cô gái trong ảnh nhảy đúng theo chuyển động của video mẫu.",
    usageCount: 0,
    rating: 5.0,
  },
  {
    id: "video-doi-thoai-nhan-vat",
    name: "Video đồng nhất nhân vật",
    description: "Tải ảnh 2 nhân vật + viết lời thoại cho từng người, AI tạo video 2 người đối thoại bằng tiếng Việt, giữ đúng gương mặt từng người.",
    category: "video",
    icon: "film",
    creditCost: 600,
    isNew: true,
    inputType: "dialogue-video",
    outputType: "video",
    inputLabel: "Lời thoại",
    inputPlaceholder: "",
    demoInput: "Nhân vật A: \"Bạn thấy chiếc váy này thế nào?\" — Nhân vật B: \"Mình thấy rất đẹp, màu này rất hợp với bạn.\"",
    demoOutput: "Video 2 nhân vật đối thoại qua lại bằng tiếng Việt, giữ đúng gương mặt từng người.",
    usageCount: 0,
    rating: 5.0,
  },
  {
    id: "video-tu-y-tuong",
    name: "Video từ ý tưởng truyện",
    description: "Nhập ý tưởng truyện + tải 1 ảnh nhân vật, AI tự chia thành nhiều phân cảnh, tạo ảnh giữ đúng nhân vật cho từng cảnh rồi động hoá thành 1 video hoàn chỉnh.",
    category: "video",
    icon: "film",
    creditCost: 900,
    isNew: true,
    inputType: "story-video",
    outputType: "video",
    inputLabel: "Ý tưởng truyện",
    inputPlaceholder: "",
    demoInput: "Cô gái bước vào quán cà phê buổi sáng, ngồi cạnh cửa sổ, mỉm cười nhìn ra ngoài, gọi 1 ly cà phê",
    demoOutput: "Video 3 phân cảnh nối tiếp nhau, giữ đúng gương mặt nhân vật, chuyển cảnh mượt mà.",
    usageCount: 0,
    rating: 5.0,
  },
  {
    id: "thay-trang-phuc",
    name: "Thay trang phục cho người mẫu",
    description: "Tải 1 ảnh người mẫu + tối đa 10 ảnh trang phục tham chiếu, AI ghép người mẫu mặc thử từng bộ đồ, giữ nguyên khuôn mặt/dáng người/bối cảnh.",
    category: "anh",
    icon: "shirt",
    creditCost: 12,
    isNew: true,
    inputType: "outfit-swap",
    outputType: "image",
    inputLabel: "Câu lệnh mô tả (có thể chỉnh sửa)",
    inputPlaceholder: "",
    demoInput: "Ảnh người mẫu + 3 ảnh trang phục tham chiếu",
    demoOutput: "3 ảnh người mẫu mặc thử 3 bộ đồ khác nhau, giữ đúng khuôn mặt và dáng người gốc.",
    usageCount: 0,
    rating: 5.0,
  },
  {
    id: "phan-tich-cam-xuc",
    name: "Phân tích cảm xúc bình luận khách hàng",
    description: "Dán danh sách bình luận, AI phân loại tích cực/tiêu cực và tóm tắt insight.",
    category: "van-ban",
    icon: "sentiment",
    creditCost: 10,
    isNew: true,
    inputType: "text",
    inputLabel: "Dán danh sách bình luận (mỗi dòng 1 bình luận)",
    inputPlaceholder: "Sản phẩm dùng tốt lắm...\nGiao hàng hơi chậm...",
    demoInput: "Sản phẩm dùng tốt lắm, sẽ ủng hộ tiếp!\nGiao hàng hơi chậm, mong cải thiện.",
    demoOutput:
      "Tích cực: 65% — khách hài lòng chất lượng sản phẩm.\nTiêu cực: 35% — chủ yếu phàn nàn về tốc độ giao hàng.\nGợi ý: cân nhắc tối ưu thời gian vận chuyển.",
    usageCount: 480,
    rating: 4.4,
  },
];
